FROM pytorch/pytorch

#RUN sudo apt update && apt-get install python3-tk

# RUN apt-get update \
#   && curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" \
#   && python3 get-pip.py \
#   && apt-get install -y \
#      python3-tk
#  # && pip3 install --upgrade pip \

# RUN pip3 --no-cache-dir install \
#     tensorflow \
#     matplotlib
#     #pyplot
#     #python-tk \
#     #six#RUN pip3 --no-cache-dir install \
#  #   tensorflow \
#   #  matplotlib
#     #pyplot
#     #python-tk \
#     #six

# COPY requirements.txt /tmp
# WORKDIR /tmp

RUN apt-get update
RUN pip install --upgrade pip
RUN apt-get install -y xvfb
# RUN pip --no-cache-dir install -r requirements.txt

RUN pip --no-cache-dir install \
    cython \
    pandas \
    numpy \
    matplotlib \
    scikit-image

COPY ./ /scripts
WORKDIR /scripts

CMD ["python", "cclass.py"]